import 'package:drift/drift.dart';

import '../../../core/date/date_range.dart';
import '../../models/transaction_filter.dart';
import '../app_database.dart';
import '../converters/date_only_converter.dart';
import '../tables/categories.dart';
import '../tables/enums.dart';
import '../tables/transactions.dart';
import '../tables/wallets.dart';

part 'transaction_dao.g.dart';

/// One category chip carried on a [TransactionListRowData]: enough to render a
/// color dot + name in Row 3 of the bespoke list item, with no follow-up query.
class TransactionRowCategory {
  const TransactionRowCategory({
    required this.id,
    required this.name,
    required this.colorValue,
  });

  final int id;
  final String name;
  final int colorValue;
}

/// Denormalized read-model for one transaction-list row, produced by the joined
/// query in [TransactionDao.watchTransactionListRows] (transaction ⨝ wallet ⨝
/// primary category). It carries exactly what the bespoke row needs, avoiding an
/// N+1 of per-row category/wallet lookups. The application layer maps it to the
/// presentational `TransactionListRow` view-model.
class TransactionListRowData {
  const TransactionListRowData({
    required this.id,
    required this.walletId,
    required this.type,
    required this.flowDirection,
    required this.status,
    required this.amountMinor,
    required this.currencyCode,
    required this.valueDate,
    required this.walletName,
    this.note,
    this.payee,
    this.categories = const <TransactionRowCategory>[],
    this.plannedAmountMinor,
    this.settledAmountMinor,
    this.isPendingParent = false,
    this.counterWalletName,
    this.isRecurring = false,
  });

  final int id;
  final int walletId;
  final TransactionType type;
  final FlowDirection flowDirection;
  final TransactionStatus status;
  final int amountMinor;
  final String currencyCode;
  final DateTime valueDate;
  final String walletName;
  final String? note;
  final String? payee;

  /// The transaction's categories (id + name + color) ordered primary-first
  /// (lowest `sortOrder`, then lowest id). Empty when it has no category links.
  /// The first entry drives the row's accent and title.
  final List<TransactionRowCategory> categories;

  // ---- Contextual Row-3 seams (PROJECT_PLAN §10.3) ----
  // These carry what later phases populate. They default to null/false today so
  // Phases 8–10 only need to start filling them (no schema/shape change here).

  /// Parent-bill planned/settled totals (Phase 9). Non-null only on parent rows.
  final int? plannedAmountMinor;
  final int? settledAmountMinor;

  /// True when this is a pending parent bill carrying a plan (Phase 9).
  final bool isPendingParent;

  /// The other leg's wallet name on a transfer (Phase 8); null otherwise.
  final String? counterWalletName;

  /// True when generated by a recurring rule (Phase 10).
  final bool isRecurring;
}

/// Data access for [Transactions] and the [TransactionCategories] junction,
/// including the transaction↔category JOIN and the balance SQL aggregate.
///
/// [Wallets] is in the accessor so the balance aggregate can read
/// `initialBalanceMinor` and register `wallets` in `readsFrom` for reactivity.
@DriftAccessor(
  tables: [Transactions, TransactionCategories, Categories, Wallets],
)
class TransactionDao extends DatabaseAccessor<AppDatabase>
    with _$TransactionDaoMixin {
  TransactionDao(super.db);

  Future<int> createTransaction(TransactionsCompanion entry) =>
      into(transactions).insert(entry);

  /// Number of transactions referencing [walletId]. Used by the undo layer to
  /// pre-check whether a wallet is FK-deletable (a wallet with ledger rows is
  /// restricted and must be archived instead).
  Future<int> countForWallet(int walletId) async {
    final Expression<int> total = countAll(
      filter: transactions.walletId.equals(walletId),
    );
    final Selectable<int> query = (selectOnly(
      transactions,
    )..addColumns(<Expression<Object>>[total])).map((row) => row.read(total)!);
    return (await query.getSingle());
  }

  /// Reactive **balance** for one wallet, in that wallet's own minor units
  /// (PROJECT_PLAN §8.1):
  ///
  ///   `initialBalanceMinor + Σ(completed inflow) − Σ(completed outflow)`
  ///
  /// Only `completed` rows count (pending/scheduled/cancelled are excluded, so
  /// pending parent bills never move a balance). Transfers DO count — each leg
  /// carries an inflow/outflow. Enum filters bind the stored index (`.index`),
  /// so this is not fragile to hardcoded literals. `?1` is reused for the
  /// wallet id in both the sub-select and the WHERE.
  Stream<int> watchWalletBalanceMinor(int walletId) {
    return customSelect(
      'SELECT COALESCE((SELECT initial_balance_minor FROM wallets '
      'WHERE id = ?1), 0) + '
      'COALESCE(SUM(CASE WHEN flow_direction = ?2 '
      'THEN amount_minor ELSE -amount_minor END), 0) AS balance '
      'FROM transactions WHERE wallet_id = ?1 AND status = ?3',
      variables: <Variable>[
        Variable.withInt(walletId),
        Variable.withInt(FlowDirection.inflow.index),
        Variable.withInt(TransactionStatus.completed.index),
      ],
      readsFrom: <ResultSetImplementation<dynamic, dynamic>>{
        transactions,
        wallets,
      },
    ).map((QueryRow row) => row.read<int>('balance')).watchSingle();
  }

  /// Reactive aggregated balance for a SET of wallets (sum of their individual
  /// balances). Meaningful only when every wallet shares a currency — mixing
  /// currencies into one integer is nonsensical, so cross-currency aggregation
  /// is deferred to Phase 7's base-currency `SummaryService`. Empty set → 0.
  Stream<int> watchWalletsBalanceMinor(Set<int> walletIds) {
    if (walletIds.isEmpty) {
      return Stream<int>.value(0);
    }
    final List<int> ids = walletIds.toList();
    final String placeholders = List<String>.filled(ids.length, '?').join(',');
    final List<Variable> variables = <Variable>[
      ...ids.map(Variable.withInt), // wallets IN (...)
      Variable.withInt(FlowDirection.inflow.index), // CASE flow
      Variable.withInt(TransactionStatus.completed.index), // WHERE status
      ...ids.map(Variable.withInt), // transactions wallet_id IN (...)
    ];
    return customSelect(
      'SELECT COALESCE((SELECT SUM(initial_balance_minor) FROM wallets '
      'WHERE id IN ($placeholders)), 0) + '
      'COALESCE(SUM(CASE WHEN flow_direction = ? '
      'THEN amount_minor ELSE -amount_minor END), 0) AS balance '
      'FROM transactions WHERE status = ? AND wallet_id IN ($placeholders)',
      variables: variables,
      readsFrom: <ResultSetImplementation<dynamic, dynamic>>{
        transactions,
        wallets,
      },
    ).map((QueryRow row) => row.read<int>('balance')).watchSingle();
  }

  Future<bool> updateTransaction(Transaction entry) =>
      update(transactions).replace(entry);

  Future<int> deleteTransaction(int id) =>
      (delete(transactions)..where((t) => t.id.equals(id))).go();

  Future<Transaction?> getTransactionById(int id) =>
      (select(transactions)..where((t) => t.id.equals(id))).getSingleOrNull();

  Stream<List<Transaction>> watchAllTransactions() =>
      (select(transactions)..orderBy([
            (t) =>
                OrderingTerm(expression: t.valueDate, mode: OrderingMode.desc),
          ]))
          .watch();

  Stream<List<Transaction>> watchTransactionsForWallet(int walletId) =>
      (select(transactions)
            ..where((t) => t.walletId.equals(walletId))
            ..orderBy([
              (t) => OrderingTerm(
                expression: t.valueDate,
                mode: OrderingMode.desc,
              ),
            ]))
          .watch();

  /// Links a category to a transaction (`allocatedAmountMinor == null` means the
  /// category covers the whole transaction).
  Future<void> addCategory(
    int transactionId,
    int categoryId, {
    int? allocatedAmountMinor,
  }) {
    return into(transactionCategories).insert(
      TransactionCategoriesCompanion.insert(
        transactionId: transactionId,
        categoryId: categoryId,
        allocatedAmountMinor: Value(allocatedAmountMinor),
      ),
    );
  }

  /// Replaces ALL category links for [transactionId] with [links] — deletes the
  /// existing set, then inserts the new one. Idempotent for a given [links] set.
  /// Callers that also mutate the transaction row wrap this in one
  /// `db.transaction(...)` for atomicity (see `TransactionRepository`).
  Future<void> replaceCategoryLinks(
    int transactionId,
    List<TransactionCategoriesCompanion> links,
  ) async {
    await (delete(
      transactionCategories,
    )..where((t) => t.transactionId.equals(transactionId))).go();
    if (links.isEmpty) {
      return;
    }
    await batch((Batch b) => b.insertAll(transactionCategories, links));
  }

  /// Field/record separators packing each transaction's category chips into one
  /// `group_concat` cell (`id␟color␟name`, chips joined by `␞`). Both are ASCII
  /// control chars (unit/record separator) that cannot occur in a category name,
  /// so parsing is unambiguous. Emitted in SQL via `char(31)` / `char(30)`.
  static final String _fieldSep = String.fromCharCode(31);
  static final String _recordSep = String.fromCharCode(30);

  static const DateOnlyConverter _dateOnly = DateOnlyConverter();

  /// Reactive, newest-first denormalized rows for the List scope, applying every
  /// predicate of [filter] **in SQL** (PROJECT_PLAN §9) and bounding the result
  /// to [limit] rows for the growing-window pagination (§10 / Phase 6). One
  /// query per row: the wallet is joined and the transaction's category chips
  /// are aggregated with `group_concat`, so there is no N+1.
  ///
  /// `readsFrom` registers every table the projection/predicates depend on, so
  /// the stream re-emits when a transaction, wallet, category, or link changes.
  Stream<List<TransactionListRowData>> watchTransactionRows(
    TransactionFilter filter, {
    required int limit,
  }) {
    final List<String> where = <String>[];
    final List<Variable> vars = <Variable>[];

    final DateRange? range = filter.range;
    if (range != null) {
      // value_date is ISO 'yyyy-MM-dd' text, so lexical compare == chronological.
      where.add('t.value_date >= ? AND t.value_date <= ?');
      vars.add(Variable.withString(_dateOnly.toSql(range.start)));
      vars.add(Variable.withString(_dateOnly.toSql(range.end)));
    }
    if (filter.walletIds.isNotEmpty) {
      final List<int> ids = filter.walletIds.toList();
      where.add('t.wallet_id IN (${_placeholders(ids.length)})');
      vars.addAll(ids.map(Variable.withInt));
    }
    if (filter.categoryIds.isNotEmpty) {
      final List<int> ids = filter.categoryIds.toList();
      where.add(
        'EXISTS (SELECT 1 FROM transaction_categories tcf '
        'WHERE tcf.transaction_id = t.id '
        'AND tcf.category_id IN (${_placeholders(ids.length)}))',
      );
      vars.addAll(ids.map(Variable.withInt));
    }
    if (filter.type != null) {
      where.add('t.type = ?');
      vars.add(Variable.withInt(filter.type!.index));
    }
    if (filter.status != null) {
      where.add('t.status = ?');
      vars.add(Variable.withInt(filter.status!.index));
    }
    final String query = filter.search.trim();
    if (query.isNotEmpty) {
      final String like = '%${_escapeLike(query)}%';
      where.add(
        r"(t.note LIKE ? ESCAPE '\' "
        r"OR t.payee LIKE ? ESCAPE '\' "
        'OR EXISTS (SELECT 1 FROM transaction_categories tcs '
        'JOIN categories cs ON cs.id = tcs.category_id '
        r"WHERE tcs.transaction_id = t.id AND cs.name LIKE ? ESCAPE '\'))",
      );
      vars
        ..add(Variable.withString(like))
        ..add(Variable.withString(like))
        ..add(Variable.withString(like));
    }

    final String whereSql = where.isEmpty
        ? ''
        : 'WHERE ${where.join(' AND ')} ';
    vars.add(Variable.withInt(limit));

    return customSelect(
      'SELECT t.id AS id, t.wallet_id AS wallet_id, t.type AS type, '
      't.flow_direction AS flow_direction, t.status AS status, '
      't.amount_minor AS amount_minor, t.currency_code AS currency_code, '
      't.value_date AS value_date, t.note AS note, t.payee AS payee, '
      't.planned_amount_minor AS planned_amount_minor, '
      't.settled_amount_minor AS settled_amount_minor, '
      't.recurring_rule_id AS recurring_rule_id, '
      't.transfer_group_id AS transfer_group_id, '
      'w.name AS wallet_name, '
      '(SELECT group_concat(chip, char(30)) FROM ('
      '  SELECT (c.id || char(31) || c.color_value || char(31) || c.name) '
      '    AS chip '
      '  FROM transaction_categories tc '
      '  JOIN categories c ON c.id = tc.category_id '
      '  WHERE tc.transaction_id = t.id '
      '  ORDER BY c.sort_order, c.id'
      ')) AS categories_blob '
      'FROM transactions t '
      'JOIN wallets w ON w.id = t.wallet_id '
      '$whereSql'
      'ORDER BY t.value_date DESC, t.id DESC '
      'LIMIT ?',
      variables: vars,
      readsFrom: <ResultSetImplementation<dynamic, dynamic>>{
        transactions,
        wallets,
        categories,
        transactionCategories,
      },
    ).watch().map(
      (List<QueryRow> rows) => rows.map(_mapListRow).toList(growable: false),
    );
  }

  TransactionListRowData _mapListRow(QueryRow row) {
    final int statusIndex = row.read<int>('status');
    final TransactionStatus status = TransactionStatus.values[statusIndex];
    final int? planned = row.read<int?>('planned_amount_minor');
    return TransactionListRowData(
      id: row.read<int>('id'),
      walletId: row.read<int>('wallet_id'),
      type: TransactionType.values[row.read<int>('type')],
      flowDirection: FlowDirection.values[row.read<int>('flow_direction')],
      status: status,
      amountMinor: row.read<int>('amount_minor'),
      currencyCode: row.read<String>('currency_code'),
      // value_date is stored as ISO 'yyyy-MM-dd' text (DateOnlyConverter).
      valueDate: DateTime.parse(row.read<String>('value_date')),
      walletName: row.read<String>('wallet_name'),
      note: row.read<String?>('note'),
      payee: row.read<String?>('payee'),
      categories: _parseChips(row.read<String?>('categories_blob')),
      plannedAmountMinor: planned,
      settledAmountMinor: row.read<int?>('settled_amount_minor'),
      isPendingParent: status == TransactionStatus.pending && planned != null,
      isRecurring: row.read<int?>('recurring_rule_id') != null,
      // The transfer counter-wallet is resolved by TransferService (Phase 8).
      counterWalletName: null,
    );
  }

  /// Parses the `group_concat` blob back into ordered chips. A malformed record
  /// (fewer than 3 fields) is skipped defensively; the name is the remainder so
  /// it is preserved even in the impossible case that it held a field separator.
  static List<TransactionRowCategory> _parseChips(String? blob) {
    if (blob == null || blob.isEmpty) {
      return const <TransactionRowCategory>[];
    }
    final List<TransactionRowCategory> chips = <TransactionRowCategory>[];
    for (final String record in blob.split(_recordSep)) {
      final List<String> f = record.split(_fieldSep);
      if (f.length < 3) {
        continue;
      }
      chips.add(
        TransactionRowCategory(
          id: int.parse(f[0]),
          colorValue: int.parse(f[1]),
          name: f.sublist(2).join(_fieldSep),
        ),
      );
    }
    return chips;
  }

  static String _placeholders(int n) => List<String>.filled(n, '?').join(',');

  /// Escapes LIKE wildcards so a user's `%`/`_`/`\` are matched literally (used
  /// with `ESCAPE '\'`).
  static String _escapeLike(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll('%', r'\%')
      .replaceAll('_', r'\_');

  /// Raw junction rows (category id + optional allocation) for [transactionId],
  /// used to prefill the edit form's category selection and splits.
  Future<List<TransactionCategory>> getCategoryLinksForTransaction(
    int transactionId,
  ) => (select(
    transactionCategories,
  )..where((t) => t.transactionId.equals(transactionId))).get();

  /// JOIN query: the categories attached to [transactionId] via the junction
  /// table. This is the DAO-boundary join required by PROJECT_PLAN Phase 1.
  Stream<List<Category>> watchCategoriesForTransaction(int transactionId) =>
      _categoriesJoin(transactionId).watch();

  Future<List<Category>> getCategoriesForTransaction(int transactionId) =>
      _categoriesJoin(transactionId).get();

  Selectable<Category> _categoriesJoin(int transactionId) {
    final JoinedSelectStatement<HasResultSet, dynamic> query =
        select(transactionCategories).join([
          innerJoin(
            categories,
            categories.id.equalsExp(transactionCategories.categoryId),
          ),
        ])..where(transactionCategories.transactionId.equals(transactionId));
    return query.map((row) => row.readTable(categories));
  }
}
